cookie:
  expiry_days: 30
  key: key
  name: name
credentials:
  usernames:
    test_user:
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Test
      last_name: User
      logged_in: False # Will be managed automatically
      password: password # Will be hashed automatically
